---
title: "M07-2-Application Assignment for R Data Types"
author: "Raymond Marquez"
date: '`r format(Sys.time())`'
format: 
  html: 
    theme: cosmo
    toc: true
    toc-location: right-body
    toc_depth: 4
    code-fold: false
    code-line-numbers: true
    code-link: true
    number-sections: true
    embed-resources: true
    df-print: paged
execute: 
  freeze: auto
  echo: fenced
  warning: false
  error: true
---

# Prompt 1

```{r}
stock_prices <- c(42.5, 43.0, 44.1, 2.7)
typeof(stock_prices)

stock_company <- c("Microsoft", "Apple", "Facebook", "Tesla")
stock_ticker  <- c("MSFT", "AAPL", "FB", "TSLA")

typeof(stock_ticker)

make_cars <- c(FALSE, FALSE, FALSE, TRUE)

stock_prices <- stock_prices + 5

names(stock_prices) <- stock_company
stock_prices
```

# Prompt 2

```{r}
stock_info.df <- data.frame(
  stock_prices,
  stock_company,
  stock_ticker,
  make_cars,
  stringsAsFactors = FALSE
)

nrow(stock_info.df)
ncol(stock_info.df)
summary(stock_info.df)

stock_info.df[stock_info.df$stock_company == "Tesla", "stock_prices"] <- 47.7
stock_info.df
```

# Prompt 3

```{r}
extra <- data.frame(
  stock_prices = 50.4,
  stock_company = "General Motors",
  stock_ticker = "GM",
  make_cars = TRUE
)

stock_info.df <- rbind(stock_info.df, extra)

rownames(stock_info.df)[nrow(stock_info.df)] <- "General Motors"

stock_info.df$open_price <- c(47.3, 47.8, 49.5, 47.9, 55.3)

stock_info.df
```

# Prompt 4

```{r}
stock_info.df$change_stock_prices_percent <- 
  (stock_info.df$stock_prices - stock_info.df$open_price) /
  stock_info.df$open_price * 100

increase <- subset(stock_info.df, change_stock_prices_percent > 0)
decrease <- subset(stock_info.df, change_stock_prices_percent < 0)

increase
decrease
```

# Prompt 5

```{r}
odd.mat <- matrix(seq(from = 1, by = 2, length.out = 50), nrow = 5)

library(tidyverse)

odd.mat2 <- seq(from = 1, by = 2, length.out = 50) |>
  matrix(nrow = 5)

odd.mat
odd.mat2
```

# Prompt 6

```{r}
library(stringr)

first_words <- str_trim(word(sentences, 1))

head(first_words, 20)

count_the <- sum(first_words == "The")
prop_the <- mean(first_words == "The")

count_the
prop_the

sentences |>
  word(1) |>
  (\(x) mean(x == "The"))
```

# Prompt 7

```{r}
library(Lahman)
library(dplyr)
library(ggplot2)

name_counts <- People |>
  filter(nameFirst %in% c("John", "Joe")) |>
  count(nameFirst)

name_counts

ggplot(name_counts, aes(nameFirst, n)) +
  geom_col() +
  labs(title = "John vs Joe",
       x = "Name",
       y = "Count")
```

# Prompt 8

```{r}
library(gapminder)
library(forcats)

levels(gapminder$continent)

pop_2007 <- gapminder |>
  filter(year == 2007) |>
  summarise(total_pop = sum(pop), .by = continent)

pop_2007

pop_2007 |>
  arrange(desc(total_pop))

gapminder1 <- gapminder |>
  mutate(continent = fct_reorder(continent, pop, sum, .desc = TRUE))

levels(gapminder1$continent)

gapminder |>
  filter(year == 2007) |>
  summarise(total_pop = sum(pop), .by = continent) |>
  ggplot(aes(fct_reorder(continent, total_pop), total_pop)) +
  geom_col() +
  coord_flip() +
  labs(title = "Population (2007)",
       x = "Continent",
       y = "Population")
```

# Prompt 9

```{r}
library(patchwork)

asia_2007 <- gapminder |>
  filter(year == 2007, continent == "Asia")

nrow(asia_2007)

top_plot <- asia_2007 |>
  slice_max(lifeExp, n = 5) |>
  ggplot(aes(fct_reorder(country, lifeExp), lifeExp)) +
  geom_col() +
  coord_flip() +
  labs(title = "Top 5")

bottom_plot <- asia_2007 |>
  slice_min(lifeExp, n = 5) |>
  ggplot(aes(fct_reorder(country, lifeExp), lifeExp)) +
  geom_col() +
  coord_flip() +
  labs(title = "Bottom 5")

top_plot + bottom_plot
```


# Prompt 10

```{r}
library(nycflights13)
library(lubridate)

glimpse(flights)

flights_lub <- flights |>
  filter(!is.na(dep_time), !is.na(arr_time), !is.na(air_time)) |>
  mutate(
    dep_time = make_datetime(year, month, day, dep_time %/% 100, dep_time %% 100),
    arr_time = make_datetime(year, month, day, arr_time %/% 100, arr_time %% 100)
  ) |>
  select(origin, dest, air_time, starts_with("dep"), starts_with("arr"))

flights_lub |>
  count(date = as.Date(dep_time)) |>
  ggplot(aes(date, n)) +
  geom_line()

flights_lub |>
  filter(month(dep_time) == 7, day(dep_time) == 4) |>
  count(hour(dep_time)) |>
  ggplot(aes(`hour(dep_time)`, n)) +
  geom_col()

flights_lub <- flights_lub |>
  mutate(
    arr_time = if_else(arr_time < dep_time, arr_time + days(1), arr_time),
    travel_time = as.numeric(arr_time - dep_time)
  )

flights_lub |>
  filter(month(dep_time) == 7, day(dep_time) == 4) |>
  ggplot(aes(air_time, travel_time)) +
  geom_point()
```